config/routes.rb
Rails.application.routes.draw do
  get 'proyects/new'
  post 'proyects/create'
  root 'proyects#new'
  get 'proyects/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyect.rb
class Proyect < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController

    http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", except: :index

  def new
    @proyect = Proyect.new
  end

  def index
    if params[:search]
      @proyects = Proyect.where(status: params[:search])

    else 
      @proyects = Proyect.all
    end
  end

  def create
    puts params
     @proyect = Proyect.new(name: params[:proyect][:name],description: params[:proyect][:description], start_date: params[:proyect][:start_date], end_date: params[:proyect][:end_date], status: params[:proyect][:status])

    if @proyect.save
      redirect_to proyects_new_path
    else
      flash[:error] = "Ocurrió un error guardando el proyecto"
      redirect_to proyects_new_path
    end 

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proyects/create.html.erb
<h1>Proyects#create</h1>
<p>Find me in app/views/proyects/create.html.erb</p>

app/views/proyects/index.html.erb
<h1> Dashboard proyectos </h1>
<%= form_tag proyects_index_path, method: :get do %>
  <%= select_tag(:search, options_for_select(['propuesta', 'progreso', 'terminado'])) %>
  <p><%= submit_tag 'Filtrar' %> </p>
<% end %>

<table class="table table-secondary">
  <thead class="thead-dark">
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Fecha_inicio</th>
      <th>Fecha_fin</th>
      <th>Estado</th>
    </tr>
  </thead>
  <tbody>
		<% @proyects.each do |proyect| %>
			<tr>
				<td><%= proyect.name %></td>
        <td><%= proyect.description %></td>
        <td><%= proyect.start_date %></td>
        <td><%= proyect.end_date %></td>
        <td><%= proyect.status %></td>
			<tr>
		<% end %>
  </tbody>
</table>

app/views/proyects/new.html.erb
<h1>¡Agrega un nuevo proyecto!</h1>
<%= form_with model: @proyect, url: proyects_create_path do |f| %>
	<p>Nombre  <%= f.text_field :name %></p>
	<p>Descripción  <%= f.text_field :description %></p>
  <p>Fecha de inicio  <%= f.date_field :start_date %></p>
  <p>Fecha de término  <%= f.date_field :end_date %></p>
  <p>Estado  <%= f.select(:status, ['propuesta', 'progreso', 'terminado']) %></p>
  <%= f.submit 'Guardar' %>
<% end %>
<br>
<br> 
<p>Apretar <%= link_to 'aquí', proyects_index_path %> para ir al dashboard</p>